name: Update and Merge Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Select input to update'
        required: true
        default: 'extraVars'
        options:
          - extraVars
          - inventory
          - deploymentManifest

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'New_branch'

  
      - name: Create prod/ directories if not exist
        run: |
          if [ ! -d "$(pwd)/prod/extraVars" ]; then
              mkdir -p $(pwd)/prod/extraVars
          fi
          if [ ! -d "$(pwd)/prod/inventory" ]; then
              mkdir -p $(pwd)/prod/inventory
          fi
          if [ ! -d "$(pwd)/prod/deploymentManifest" ]; then
              mkdir -p $(pwd)/prod/deploymentManifest
          fi
          ls -l $(pwd)/prod

      - name: path
        run: |
          pwd
          echo "Current directory: $(pwd)"
          ls -l $(pwd)/non-prod/extraVars/




      - name: Git Commit
        run: |
          ls -l $(pwd)/prod
          git add --all
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Automated update of dropdown inputs"
          git checkout -b New_branch

    

      - name: Git Push
        run: git push -u origin New_branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update ${{ github.event.inputs.choice }} dropdown inputs"
          branch: update-${{ github.event.inputs.choice }}-inputs
          commit-message: "Automated update of ${{ github.event.inputs.choice }} dropdown inputs"
          body: |
            Automated update of ${{ github.event.inputs.choice }} dropdown inputs.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve pull request
        if: steps.create_pr.outcome == 'success'
        id: approve_pr
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create_pr.outputs.pr_number }}
          repo: ${{ env.DESTINATION_GITHUB_ORG }}/${{ env.DESTINATION_REPO_NAME }}

      - name: Merge pull Request
        if: steps.create_pr.outcome == 'success' && steps.approve_pr.outcome == 'success'
        id: merge_pr
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.ANIKET_TEST_TOKEN }}
          PULL_REQUEST: ${{ env.DESTINATION_GITHUB_ORG }}/${{ env.DESTINATION_REPO_NAME }}/${{ steps.create_pr.outputs.pr_number }}
          UPDATE_METHOD: merge

      - name: Delete merge branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.ANIKET_TEST_TOKEN }}
          owner: ${{ env.DESTINATION_GITHUB_ORG }}
          repository: ${{ env.DESTINATION_REPO_NAME }}
          branches: ${{ env.TEMP_BRANCH }}
