name: Copy code to prod directories

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Select input to update'
        # required: true
        default: 'extraVars'
        options:
          - extraVars
          - inventory
          - deploymentManifest

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.ANAND_TEST_TOKEN }}
        with:
          branch: 'update-${{ github.event.inputs.choice }}-inputs'

      - name: Verify Branch Creation  
        run: echo "Branch created:${{ steps.create_branch.outputs.branch }}"

      - name: Create prod/ directories if not exist
        run: |
          if [ ! -d "$(pwd)/prod/extraVars" ]; then
              mkdir -p $(pwd)/prod/extraVars
              touch $(pwd)/prod/extraVars/README.md
          fi
          if [ ! -d "$(pwd)/prod/inventory" ]; then
              mkdir -p $(pwd)/prod/inventory
              touch $(pwd)/prod/inventory/README.md
          fi
          if [ ! -d "$(pwd)/prod/deploymentManifest" ]; then
              mkdir -p $(pwd)/prod/deploymentManifest
              touch $(pwd)/prod/deploymentManifest/README.md
          fi
          ls -l $(pwd)/prod

     
