name: Update and Merge Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Select input to update: extraVars, inventory, deploymentManifest'
        required: true
        default: 'extraVars'
        options:
          extraVars: 'Update extraVars'
          inventory: 'Update inventory'
          deploymentManifest: 'Update deploymentManifest'

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
          path: job_repo

      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'new_branch'

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: new_branch
          path: job_repo

      - name: Create Directories
        run: |
          # mkdir -p job_repo/prod/extraVars
          mkdir -p prod/inventory/test.txt
          # mkdir -p job_repo/prod/deploymentManifest

      - name: path
        run: |
          pwd
      - name: Update Inputs
        run: |
          choice="${{ github.event.inputs.choice }}"
          case $choice in
            "extraVars")
              cp non-prod/extraVars/*.json prod/extraVars/
              ;;
            "inventory")
              cp non-prod/inventory/*.json prod/inventory/
              ;;
            "deploymentManifest")
              cp non-prod/deploymentManifest/*.json prod/deploymentManifest/
              ;;
            *)
              echo "Invalid choice"
              exit 1
              ;;
          esac
          echo "Inputs updated for $choice"

      - name: Git Add
        run: git add .

      - name: Git Commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Automated update of ${{ github.event.inputs.choice }} dropdown inputs"

      - name: Git Push
        run: git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update ${{ github.event.inputs.choice }} dropdown inputs"
          branch: update-${{ github.event.inputs.choice }}-inputs
          commit-message: "Automated update of ${{ github.event.inputs.choice }} dropdown inputs"
          body: |
            Automated update of ${{ github.event.inputs.choice }} dropdown inputs.
          token: ${{ secrets.GITHUB_TOKEN }}
